'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Agendas', [
      {
        date: '3 Oct 2021 12:00:00 GMT-0400',
        is5thSunday: false,
        isDaylightSavingsChange: false,
        isFastSunday: false,
        isGeneralConference: true,
        isMeetingTimeChange: false,
        isPrimaryProgram: false,
        isStakeConference: false,
        isWardConference: false,
        name: 'Oct-A',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        date: '10 Oct 2021 12:00:00 GMT-0400',
        is5thSunday: false,
        isDaylightSavingsChange: false,
        isFastSunday: true,
        isGeneralConference: true,
        isMeetingTimeChange: false,
        isPrimaryProgram: false,
        isStakeConference: false,
        isWardConference: false,
        name: 'Oct-B',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        date: '17 Oct 2021 12:00:00 GMT-0400',
        is5thSunday: false,
        isDaylightSavingsChange: false,
        isFastSunday: false,
        isGeneralConference: true,
        isMeetingTimeChange: false,
        isPrimaryProgram: false,
        isStakeConference: false,
        isWardConference: false,
        name: 'Oct-C',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        date: '24 Oct 2021 12:00:00 GMT-0400',
        is5thSunday: false,
        isDaylightSavingsChange: false,
        isFastSunday: false,
        isGeneralConference: true,
        isMeetingTimeChange: false,
        isPrimaryProgram: false,
        isStakeConference: false,
        isWardConference: false,
        name: 'Oct-D',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        date: '31 Oct 2021 12:00:00 GMT-0400',
        is5thSunday: true,
        isDaylightSavingsChange: false,
        isFastSunday: false,
        isGeneralConference: true,
        isMeetingTimeChange: false,
        isPrimaryProgram: false,
        isStakeConference: false,
        isWardConference: false,
        name: 'Oct-E',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        date: '7 Nov 2021 12:00:00 GMT-0400',
        is5thSunday: false,
        isDaylightSavingsChange: true,
        isFastSunday: true,
        isGeneralConference: true,
        isMeetingTimeChange: false,
        isPrimaryProgram: false,
        isStakeConference: false,
        isWardConference: false,
        name: 'Nov-A',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        date: '14 Nov 2021 12:00:00 GMT-0400',
        is5thSunday: false,
        isDaylightSavingsChange: false,
        isFastSunday: false,
        isGeneralConference: true,
        isMeetingTimeChange: false,
        isPrimaryProgram: true,
        isStakeConference: false,
        isWardConference: false,
        name: 'Nov-B',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        date: '21 Nov 2021 12:00:00 GMT-0400',
        is5thSunday: false,
        isDaylightSavingsChange: false,
        isFastSunday: false,
        isGeneralConference: true,
        isMeetingTimeChange: false,
        isPrimaryProgram: false,
        isStakeConference: false,
        isWardConference: false,
        name: 'Nov-C',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        date: '28 Nov 2021 12:00:00 GMT-0400',
        is5thSunday: false,
        isDaylightSavingsChange: false,
        isFastSunday: false,
        isGeneralConference: true,
        isMeetingTimeChange: false,
        isPrimaryProgram: false,
        isStakeConference: false,
        isWardConference: false,
        name: 'Nov-D',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        date: '5 Dec 2021 12:00:00 GMT-0400',
        is5thSunday: false,
        isDaylightSavingsChange: false,
        isFastSunday: true,
        isGeneralConference: true,
        isMeetingTimeChange: false,
        isPrimaryProgram: false,
        isStakeConference: false,
        isWardConference: false,
        name: 'Dec-A',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        date: '12 Dec 2021 12:00:00 GMT-0400',
        is5thSunday: false,
        isDaylightSavingsChange: false,
        isFastSunday: false,
        isGeneralConference: true,
        isMeetingTimeChange: false,
        isPrimaryProgram: false,
        isStakeConference: false,
        isWardConference: false,
        name: 'Dec-B',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        date: '19 Dec 2021 12:00:00 GMT-0400',
        is5thSunday: false,
        isDaylightSavingsChange: false,
        isFastSunday: false,
        isGeneralConference: true,
        isMeetingTimeChange: false,
        isPrimaryProgram: false,
        isStakeConference: false,
        isWardConference: false,
        name: 'Dec-C',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        date: '26 Dec 2021 12:00:00 GMT-0400',
        is5thSunday: false,
        isDaylightSavingsChange: false,
        isFastSunday: false,
        isGeneralConference: true,
        isMeetingTimeChange: false,
        isPrimaryProgram: false,
        isStakeConference: false,
        isWardConference: false,
        name: 'Dec-D',
        createdAt: new Date(),
        updatedAt: new Date()
      },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Agendas', null, {});
  }
};
